# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8b37fe48e824c666f0878d0c4c93e65a9ee093079537c78f3f3ce55cbb9425749785837579d23656f43fae0117fcb554a3aaa9acc5b7be231afbc082ee26c55d

test:
  secret_key_base: a4a3677fa406c12f66a8f2e03b2e1cf675a5dd2e36fd86ad5b082fd2e6476e830eb1db5bd1ef1d040f8922ae624437e1da03c721b9ce36f6e17947597bdbc0fb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
